### ISSUE TITLE
Cannot build fibers on Arch Linux

### ISSUE THREAD

**Issue by dessaya** [laverdet/node-fibers#321]
Hi, I'm getting this error when running `npm install`:

```
> fibers@1.0.15 install /home/diego/repos/brainiac-www/node_modules/fibers
> node build.js || nodejs build.js

[... several warnings ...]

  CC(target) Release/obj.target/fibers/src/libcoro/coro.o
In file included from /usr/include/ucontext.h:26:0,
                 from ../src/libcoro/coro.h:321,
                 from ../src/libcoro/coro.c:41:
/usr/include/sys/ucontext.h:137:5: error: unknown type name ‘stack_t’
     stack_t uc_stack;
     ^~~~~~~
../src/libcoro/coro.c: In function ‘coro_init’:
../src/libcoro/coro.c:93:3: warning: implicit declaration of function ‘asm’ [-Wimplicit-function-declaration]
   asm (".cfi_undefined rip");
   ^~~
../src/libcoro/coro.c: In function ‘coro_create’:
../src/libcoro/coro.c:383:19: error: request for member ‘ss_sp’ in something not a structure or union
   ctx->uc.uc_stack.ss_sp    = sptr;
                   ^
../src/libcoro/coro.c:384:19: error: request for member ‘ss_size’ in something not a structure or union
   ctx->uc.uc_stack.ss_size  = (size_t)ssize;
                   ^
../src/libcoro/coro.c:385:19: error: request for member ‘ss_flags’ in something not a structure or union
   ctx->uc.uc_stack.ss_flags = 0;
                   ^
make: *** [fibers.target.mk:104: Release/obj.target/fibers/src/libcoro/coro.o] Error 1
make: Leaving directory '/home/diego/repos/brainiac-www/node_modules/fibers/build'
```

[Apparently](http://stackoverflow.com/questions/32426835/glibc-error-in-ucontext-h-but-only-with-std-c11) `stack_t` is not standard and you need to pass `-gnu11` to gcc.

Thanks!

**Comment by laverdet** [comment]
What OS, OS version, node version, and gcc version are you running?

**Comment by dessaya** [comment]
OS: Arch Linux, rolling release so I don't think OS version applies
node v7.1.0
gcc 6.2.1

**Comment by AccaliaDeElementia** [comment]
Travis also cannot build fibers under Nodejs version 7.1.0:

https://travis-ci.org/SockDrawer/SockRPG/jobs/177646164

**Comment by xpepermint** [comment]
The same with https://circleci.com

**Comment by vampolo** [comment]
Found the same problem as @AccaliaDeElementia . Any idea what is going wrong on node 7.x ?

**Comment by vampolo** [comment]
From what i'm seeing seems related to the g++ version. 
Was able to compile it on mac where g++ is LLVM 8 with clang. Wasn't able to compile on linux with g++ 4.4.7

**Comment by laverdet** [comment]
Try adding -gnu11 to the compiler flags like the original submitter advised, let me know if that works for you

**Comment by xpepermint** [comment]
Any progress?

**Comment by laverdet** [comment]
Try adding -gnu11 to the compiler flags like the original submitter advised, let me know if that works for you

**Comment by dessaya** [comment]
@laverdet It worked with `CFLAGS=-std=gnu11 npm install`

**Comment by g4jc** [comment]
I tried with CFLAGS but was still unable to get it to work, latest Arch 64bit.
Log of npm install: https://clbin.com/L0a6a

**Comment by jlchereau** [comment]
Getting ```cc1: error: unrecognized command line option ‘-std=gnu11’``` on Travis-CI since fibers v1.0.16 (v1.0.15 and before were working fine) with :
- nodejs 4, 5 and 7 (not 6 and 8) 
- g++ 4.8 and 4.9
- with/without environment CFLAGS=-std=gnu11

**Comment by laverdet** [comment]
@jlchereau thanks for the heads up. I updated the travis config file w/ 164924677aab361755d90e01ee2ff4491deabe14
