### ISSUE TITLE
doesn't build on macOS 10.14.1 w/ node 11.1.0

### ISSUE THREAD

**Issue by vobu** [laverdet/node-fibers#396]
got this while trying to install `synchronize` https://www.npmjs.com/package/synchronize on
- macOS 10.14.1
- node 11.1.0
~~~
../src/fibers.cc:795:84: error: too few arguments to function call, expected at least 3, have 2
                        fn->SetAccessor(uni::NewLatin1Symbol(isolate, "fibersCreated"), GetFibersCreated);
~~~
-> build and install failed

Downgrading `node` to lts `8.12.0` made the build and install work.

Here's the full log:
~~~
box: ~/some/dir > nvm ls
->      v11.1.0

box: ~/some/dir > npm install synchronize --save

> fibers@1.0.15 install /Users/<user>/some/dir/node_modules/fibers
> node build.js || nodejs build.js

  CXX(target) Release/obj.target/fibers/src/fibers.o
../src/fibers.cc:122:64: error: too few arguments to function call, expected at least 3, have 2
                return String::NewFromOneByte(isolate, (const uint8_t*)string);
                       ~~~~~~~~~~~~~~~~~~~~~~                                ^
/Users/<user>/.node-gyp/11.1.0/include/node/v8.h:2897:3: note: 'NewFromOneByte' declared here
  static V8_WARN_UNUSED_RESULT MaybeLocal<String> NewFromOneByte(
  ^
../src/fibers.cc:126:64: error: too few arguments to function call, expected at least 3, have 2
                return String::NewFromOneByte(isolate, (const uint8_t*)string);
                       ~~~~~~~~~~~~~~~~~~~~~~                                ^
/Users/<user>/.node-gyp/11.1.0/include/node/v8.h:2897:3: note: 'NewFromOneByte' declared here
  static V8_WARN_UNUSED_RESULT MaybeLocal<String> NewFromOneByte(
  ^
../src/fibers.cc:406:24: warning: 'Utf8Value' is deprecated: Use Isolate version [-Wdeprecated-declarations]
                                        String::Utf8Value stack(uni::Deref(that.isolate, fatal_stack));
                                                          ^
/Users/<user>/.node-gyp/11.1.0/include/node/v8.h:2991:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/<user>/.node-gyp/11.1.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/fibers.cc:433:80: error: no matching member function for call to 'NewInstance'
                                return uni::Return(uni::Deref(Isolate::GetCurrent(), tmpl)->GetFunction()->NewInstance(1, argv), args);
                                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
/Users/<user>/.node-gyp/11.1.0/include/node/v8.h:4102:44: note: candidate function not viable: requires single argument 'context', but 2 arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                           ^
/Users/<user>/.node-gyp/11.1.0/include/node/v8.h:4099:44: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                           ^
../src/fibers.cc:621:14: error: no matching constructor for initialization of 'v8::TryCatch'
                                TryCatch try_catch;
                                         ^
/Users/<user>/.node-gyp/11.1.0/include/node/v8.h:8815:12: note: candidate constructor not viable: requires single argument 'isolate', but no arguments were provided
  explicit TryCatch(Isolate* isolate);
           ^
/Users/<user>/.node-gyp/11.1.0/include/node/v8.h:8934:3: note: candidate constructor not viable: requires 1 argument, but 0 were provided
  TryCatch(const TryCatch&) = delete;
  ^
../src/fibers.cc:628:66: error: too few arguments to function call, expected at least 2, have 1
                                Script::Compile(uni::NewLatin1String(that.isolate, "void 0;"));
                                ~~~~~~~~~~~~~~~                                              ^
/Users/<user>/.node-gyp/11.1.0/include/node/v8.h:1359:3: note: 'Compile' declared here
  static V8_WARN_UNUSED_RESULT MaybeLocal<Script> Compile(
  ^
../src/fibers.cc:741:34: error: no matching member function for call to 'ToNumber'
                        Coroutine::pool_size = value->ToNumber()->Value();
                                               ~~~~~~~^~~~~~~~
/Users/<user>/.node-gyp/11.1.0/include/node/v8.h:2519:44: note: candidate function not viable: requires single argument 'context', but no arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Number> ToNumber(
                                           ^
/Users/<user>/.node-gyp/11.1.0/include/node/v8.h:2536:31: note: candidate function not viable: requires single argument 'isolate', but no arguments were provided
                Local<Number> ToNumber(Isolate* isolate) const);
                              ^
../src/fibers.cc:793:72: error: too few arguments to function call, expected at least 3, have 2
                        fn->SetAccessor(uni::NewLatin1Symbol(isolate, "current"), GetCurrent);
                        ~~~~~~~~~~~~~~~                                                     ^
/Users/<user>/.node-gyp/11.1.0/include/node/v8.h:3454:3: note: 'SetAccessor' declared here
  V8_WARN_UNUSED_RESULT Maybe<bool> SetAccessor(
  ^
/Users/<user>/.node-gyp/11.1.0/include/node/v8config.h:418:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/fibers.cc:794:63: error: no viable conversion from 'uni::FunctionType (Local<v8::String>, const uni::GetterCallbackInfo &)' (aka 'void (Local<v8::String>, const PropertyCallbackInfo<v8::Value> &)') to 'Local<v8::Name>'
                        fn->SetAccessor(uni::NewLatin1Symbol(isolate, "poolSize"), GetPoolSize, SetPoolSize);
                                                                                   ^~~~~~~~~~~
/Users/<user>/.node-gyp/11.1.0/include/node/v8.h:303:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'uni::FunctionType (Local<v8::String>, const uni::GetterCallbackInfo &)' (aka 'void (Local<v8::String>, const PropertyCallbackInfo<v8::Value> &)') to 'const v8::Local<v8::Name> &' for 1st argument
class Local {
      ^
/Users/<user>/.node-gyp/11.1.0/include/node/v8.h:303:7: note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'uni::FunctionType (Local<v8::String>, const uni::GetterCallbackInfo &)' (aka 'void (Local<v8::String>, const PropertyCallbackInfo<v8::Value> &)') to 'v8::Local<v8::Name> &&' for 1st argument
/Users/<user>/.node-gyp/11.1.0/include/node/v8.h:307:13: note: candidate template ignored: could not match 'Local<type-parameter-0-0>' against 'void (*)(v8::Local<v8::String>, const v8::PropertyCallbackInfo<v8::Value> &)'
  V8_INLINE Local(Local<S> that)
            ^
/Users/<user>/.node-gyp/11.1.0/include/node/v8.h:3455:43: note: passing argument to parameter 'name' here
      Local<Context> context, Local<Name> name,
                                          ^
../src/fibers.cc:795:84: error: too few arguments to function call, expected at least 3, have 2
                        fn->SetAccessor(uni::NewLatin1Symbol(isolate, "fibersCreated"), GetFibersCreated);
                        ~~~~~~~~~~~~~~~                                                                 ^
/Users/<user>/.node-gyp/11.1.0/include/node/v8.h:3454:3: note: 'SetAccessor' declared here
  V8_WARN_UNUSED_RESULT Maybe<bool> SetAccessor(
  ^
/Users/<user>/.node-gyp/11.1.0/include/node/v8config.h:418:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
In file included from ../src/fibers.cc:1:
In file included from ../src/coroutine.h:1:
In file included from /Users/<user>/.node-gyp/11.1.0/include/node/node.h:63:
/Users/<user>/.node-gyp/11.1.0/include/node/v8.h:314:5: error: assigning to 'v8::Context *' from incompatible type 'v8::String *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/<user>/.node-gyp/11.1.0/include/node/v8.h:268:39: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                      ^~~~~~~~~~~~~~~~~~
../src/fibers.cc:794:20: note: in instantiation of function template specialization 'v8::Local<v8::Context>::Local<v8::String>' requested here
                        fn->SetAccessor(uni::NewLatin1Symbol(isolate, "poolSize"), GetPoolSize, SetPoolSize);



box: ~/some/dir > nvm use lts/carbon; node --version

v8.12.0
Naunet: ~/some/dir [master !?+*]> npm install synchronize --save

> fibers@1.0.15 install /Users/<user>/some/dir/node_modules/fibers
> node build.js || nodejs build.js

  CXX(target) Release/obj.target/fibers/src/fibers.o
../src/fibers.cc:122:18: warning: 'NewFromOneByte' is deprecated [-Wdeprecated-declarations]
                return String::NewFromOneByte(isolate, (const uint8_t*)string);
                               ^
/Users/<user>/.node-gyp/8.12.0/include/node/v8.h:2729:10: note: 'NewFromOneByte' has been explicitly marked deprecated here
  static V8_DEPRECATED(
         ^
/Users/<user>/.node-gyp/8.12.0/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/fibers.cc:126:18: warning: 'NewFromOneByte' is deprecated [-Wdeprecated-declarations]
                return String::NewFromOneByte(isolate, (const uint8_t*)string);
                               ^
/Users/<user>/.node-gyp/8.12.0/include/node/v8.h:2729:10: note: 'NewFromOneByte' has been explicitly marked deprecated here
  static V8_DEPRECATED(
         ^
/Users/<user>/.node-gyp/8.12.0/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/fibers.cc:433:80: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
                                return uni::Return(uni::Deref(Isolate::GetCurrent(), tmpl)->GetFunction()->NewInstance(1, argv), args);
                                                                                                           ^
/Users/<user>/.node-gyp/8.12.0/include/node/v8.h:3896:3: note: 'NewInstance' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/<user>/.node-gyp/8.12.0/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/fibers.cc:621:14: warning: 'TryCatch' is deprecated [-Wdeprecated-declarations]
                                TryCatch try_catch;
                                         ^
/Users/<user>/.node-gyp/8.12.0/include/node/v8.h:8365:3: note: 'TryCatch' has been explicitly marked deprecated here
  V8_DEPRECATED("Use isolate version", TryCatch());
  ^
/Users/<user>/.node-gyp/8.12.0/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/fibers.cc:741:34: warning: 'ToNumber' is deprecated [-Wdeprecated-declarations]
                        Coroutine::pool_size = value->ToNumber()->Value();
                                                      ^
/Users/<user>/.node-gyp/8.12.0/include/node/v8.h:2383:10: note: 'ToNumber' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Number> ToNumber() const);
         ^
/Users/<user>/.node-gyp/8.12.0/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/fibers.cc:793:8: warning: 'SetAccessor' is deprecated [-Wdeprecated-declarations]
                        fn->SetAccessor(uni::NewLatin1Symbol(isolate, "current"), GetCurrent);
                            ^
/Users/<user>/.node-gyp/8.12.0/include/node/v8.h:3229:3: note: 'SetAccessor' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/<user>/.node-gyp/8.12.0/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/fibers.cc:794:8: warning: 'SetAccessor' is deprecated [-Wdeprecated-declarations]
                        fn->SetAccessor(uni::NewLatin1Symbol(isolate, "poolSize"), GetPoolSize, SetPoolSize);
                            ^
/Users/<user>/.node-gyp/8.12.0/include/node/v8.h:3229:3: note: 'SetAccessor' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/<user>/.node-gyp/8.12.0/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/fibers.cc:795:8: warning: 'SetAccessor' is deprecated [-Wdeprecated-declarations]
                        fn->SetAccessor(uni::NewLatin1Symbol(isolate, "fibersCreated"), GetFibersCreated);
                            ^
/Users/<user>/.node-gyp/8.12.0/include/node/v8.h:3229:3: note: 'SetAccessor' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/<user>/.node-gyp/8.12.0/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
8 warnings generated.
  CXX(target) Release/obj.target/fibers/src/coroutine.o
  CC(target) Release/obj.target/fibers/src/libcoro/coro.o
  SOLINK_MODULE(target) Release/fibers.node
~~~

**Comment by vobu** [comment]
on top, even though the build seems to work, running into the same issue as in #393 when trying to use `fibers` at runtime:
~~~
## There is an issue with `node-fibers` ##
`/Users/<user>/some/dir/node_modules/fibers/bin/darwin-x64-64/fibers.node` is missing.
~~~

**Comment by laverdet** [comment]
Ok there's a lot to unpack here..
- Odd-numbered versions of nodejs are basically in beta. Fibers sometimes supports these versions but it's best to stick to even-numbered stable versions.
- fibers@1.0.15 is very old and only supports node v4.x - v8.x if I remember correctly. I would recommend using 3.0.0 which has a backwards compatible API but supports newer versions of nodejs.
- The "There is an issue with `node-fibers`" message happens when the version of nodejs you used to install fibers is different than the version you are currently running. `nvm` has caused problems like this in the past where `npm` will run a different version of node than `nodejs`. #393 is not related and has to do with Webpack.
